# Generated by Django 4.1.7 on 2023-04-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
