# Generated by Django 4.1.7 on 2023-04-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_wellnesscategory_wellnesstags_wellness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellness',
            name='tags',
            field=models.ManyToManyField(to='travel.wellnesstags'),
        ),
    ]
