# Generated by Django 4.1.7 on 2023-04-22 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel', '0006_alter_wellnesstags_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GearCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Gear Reviews', 'Gear Reviews'), ('Gear Guides', 'Gear Guides'), ('Travel Gadgets', 'Travel Gadgets'), ('Outdoor Gear', 'Outdoor Gear')], max_length=50)),
                ('slug', models.SlugField(editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GearTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Backpacks', 'Backpacks'), ('Travel Clothing', 'Travel Clothing'), ('Travel Accessories', 'Travel Accessories'), ('Camera Gear', 'Camera Gear'), ('Hiking Gear', 'Hiking Gear'), ('Travel Tech', 'Travel Tech'), ('Apps', 'Apps')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('image_url_1', models.URLField(blank=True, null=True)),
                ('image_url_2', models.URLField(blank=True, null=True)),
                ('image_url_3', models.URLField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.gearcategory')),
                ('tags', models.ManyToManyField(to='travel.geartags')),
            ],
        ),
    ]
