# Generated by Django 4.1.7 on 2023-04-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_gearcategory_geartags_gear'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
