# Generated by Django 4.1.7 on 2023-04-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_gear_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Destinations', 'Destinations'), ('Travel Tips & Guides', 'Travel Tips & Guides'), ('Adventure Travel', 'Adventure Travel'), ('Travel Storie', 'Travel Stories')], max_length=50),
        ),
        migrations.AlterField(
            model_name='wellnesscategory',
            name='name',
            field=models.CharField(choices=[('Wellness Retreats', 'Wellness Retreats'), ('Mindfulness & Mental Health', 'Mindfulness & Mental Health'), ('Food & Nutrition', 'Food & Nutrition'), ('Fitness & Exercise', 'Fitness & Exercise'), ('Personal Wellness Storie', 'Personal Wellness Stories')], max_length=50),
        ),
        migrations.AlterField(
            model_name='wellnesstags',
            name='name',
            field=models.CharField(choices=[('stress_management', 'Stress Management'), ('mental_health', 'Mental Health'), ('workout', 'Workouts'), ('food', 'Food'), ('recepies', 'Recepies'), ('hotel_fitness', 'Hotel Fitness')], max_length=50),
        ),
    ]
